FROM node:13-alpine
LABEL maintainer="mike.williamson@cds-snc.ca"

WORKDIR /app
COPY . .

RUN npm install

ENV NODE_ENV development
RUN npm run build

USER node

EXPOSE 3000
CMD ["npm", "run", "dev"]
