apiVersion: skaffold/v1
kind: Config
metadata:
  name: skaffold-create-react-app
build:
  artifacts:
  - image: gaap-frontend
    context: frontend
    sync:
      infer:
      - '**/*.js'
      - '**/*.css'
    docker:
      dockerfile: Dockerfile.dev
  - image: gaap-api
    context: api
    sync:
      infer:
      - '**/*.js'
      - '**/*.css'
deploy:
  kustomize:
    path: platform/overlays/minikube
portForward:
- resourceType: service
  resourceName: gaap-frontend
  port: 3000
  localPort: 3000
- resourceType: service
  resourceName: gaap-api
  port: 3000
  localPort: 3001
