apiVersion: apps/v1
kind: Deployment
metadata:
  name: gaap-api
spec:
  selector:
    matchLabels:
      app: gaap-api
  template:
    metadata:
      labels:
        app: gaap-api
    spec:
      containers:
      - name: gaap-api
        image: gaap-api
        ports:
        - containerPort: 3000
