apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gaap-frontend
  name: gaap-frontend
spec:
  ports:
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: gaap-frontend
  type: LoadBalancer
status:
  loadBalancer: {}
